### ISSUE TITLE
Handle prefixed (and in-middle), possibly multiple terms

### ISSUE THREAD

**Issue by petri** [psolin/cleanco#8]
In Finland, you sometimes see the format "Oy Corporation Ab" where "Oy" refers to limited liability (in Finnish) and "Ab" the same (in Swedish, the other official language of Finland).

In other words, the abbreviations can also appear in front of the company name - or both before and after.

**Comment by psolin** [comment]
I'll probably have to write a separate little bit of code to tackle this.

The code is very much ethnocentric as it stands.

**Comment by petri** [comment]
Ok. I just found out that in Finland the terms ("Oy" for example) can appear also in the middle. It's not very common, but not exactly very rare either.

I would like to suggest that terms be removed wherever they are found, as long as they are wrapped in name start/end and/or whitespace. 

But given that the library removes all terms it finds in its database (ie. terms for all countries), I wonder if some legitimate company name parts will then accidentally be removed? On the other hand, that is a possibility now already.

Perhaps an option could be added to the library to remedy that so that only an user-selectable portion of the dataset be used for terms that be removed?

**Comment by psolin** [comment]
> On the other hand, that is a possibility now already, albeit a smaller one.

Because most company names in the West are written this way, it is really the one kind of fool-proof way that the code can do its thing, at least in English speaking countries like the US/UK.

Since you are here, let me tell you what this was originally used for.

I worked for a company that was trying to compare new marketing records (of individuals) with existing ones.  Of course, they didn't want to add an additional record for someone who already existed.  The way that they compared company names before I wrote this was weird -- their database guy would just compare the first three letters of the company, and if it were a match, then the person would not be added.  You can imagine that for common names and companies that start with the first three letters, a number of people would not be added to the database.  Cleaning up company names was also a problem -- the LTD, INC, LLC entities should have been stripped from the end of the company to keep it standardized.  One standard for company names could unite many many records.  Country discovery could feasibly done with this little bit of information, too.

I wrote about the problem more in depth on my blog: http://paulsolin.com/2014/03/27/comparing-company-names/

Anyway, of course you can provide an implementation, like a parameter that is selected.  As I no longer work for this place, and all of the code was written on my own free time, I want to make it accessible to as many people as possible.
